#!/usr/bin/env python3
"""Audit the complete HHR release for private data and publication hygiene."""

from __future__ import annotations

import argparse
import io
from pathlib import Path
import re
import sys
import tokenize


TEXT_SUFFIXES = {
    ".c", ".cc", ".cpp", ".cu", ".cuh", ".h", ".hpp", ".ini",
    ".json", ".md", ".py", ".sh", ".toml", ".txt", ".yaml", ".yml",
}
FORBIDDEN_SUFFIXES = {
    ".bin", ".ckpt", ".log", ".o", ".pt", ".pth", ".pyc", ".so",
}
FORBIDDEN_PARTS = {"__pycache__", ".pytest_cache", "outputs"}
PRIVATE_PATTERNS = {
    "absolute home path": re.compile(r"/(?:home|Users)/[^/\s]+/"),
    "internal data path": re.compile(r"/data/[^\s'\"]+"),
    "email address": re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.I),
    "IPv4 address": re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"),
    "private key": re.compile(r"BEGIN (?:RSA |OPENSSH )?PRIVATE KEY"),
    "credential token": re.compile(r"(?:api[_-]?key|access[_-]?token|secret)\s*[:=]", re.I),
    "generation provenance": re.compile(
        r"generated by (?:an )?automated assistant|automated assistant disclaimer",
        re.I,
    ),
}
HAN = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff]")


def python_comments(text: str):
    try:
        tokens = tokenize.generate_tokens(io.StringIO(text).readline)
        for token in tokens:
            if token.type == tokenize.COMMENT:
                yield token.start[0], token.string
    except (IndentationError, SyntaxError, tokenize.TokenError):
        return


def native_comments(text: str):
    in_block = False
    for number, line in enumerate(text.splitlines(), 1):
        fragment = line
        if in_block:
            end = fragment.find("*/")
            if end < 0:
                yield number, fragment
                continue
            yield number, fragment[: end + 2]
            fragment = fragment[end + 2 :]
            in_block = False
        while fragment:
            line_pos = fragment.find("//")
            block_pos = fragment.find("/*")
            positions = [pos for pos in (line_pos, block_pos) if pos >= 0]
            if not positions:
                break
            start = min(positions)
            if start == line_pos:
                yield number, fragment[start:]
                break
            end = fragment.find("*/", start + 2)
            if end < 0:
                yield number, fragment[start:]
                in_block = True
                break
            yield number, fragment[start : end + 2]
            fragment = fragment[end + 2 :]


def shell_comments(text: str):
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.lstrip()
        if stripped.startswith("#") and not stripped.startswith("#!"):
            yield number, stripped


def audit(root: Path) -> list[str]:
    failures = []
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if any(part in FORBIDDEN_PARTS for part in relative.parts):
            failures.append(f"forbidden path: {relative}")
            continue
        if not path.is_file():
            continue
        if path.suffix.lower() in FORBIDDEN_SUFFIXES:
            failures.append(f"forbidden artifact: {relative}")
            continue
        if path.suffix.lower() not in TEXT_SUFFIXES and path.name != "CMakeLists.txt":
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            failures.append(f"non-UTF-8 source: {relative}")
            continue
        if HAN.search(text):
            failures.append(f"Chinese text: {relative}")
        if relative != Path("tests/audit_release.py"):
            for label, pattern in PRIVATE_PATTERNS.items():
                if pattern.search(text):
                    failures.append(f"{label}: {relative}")
        if path.suffix == ".py":
            comments = python_comments(text)
        elif path.suffix in {".c", ".cc", ".cpp", ".cu", ".cuh", ".h", ".hpp"}:
            comments = native_comments(text)
        elif path.suffix == ".sh":
            comments = shell_comments(text)
        else:
            comments = ()
        for number, comment in comments:
            if HAN.search(comment):
                failures.append(f"Chinese source comment: {relative}:{number}")
    return failures


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", nargs="?", type=Path, default=Path.cwd())
    args = parser.parse_args()
    root = args.root.resolve()
    failures = audit(root)
    if failures:
        print("\n".join(failures))
        raise SystemExit(1)
    print(f"release audit passed: {root}")


if __name__ == "__main__":
    main()
